### ISSUE TITLE
Customise the time to lock wallet

### ISSUE THREAD

**Issue by am1993421** [tahowallet/extension#3158] opened 2023-03-15 11:16 UTC
### Discord Discussion Link

https://discord.com/channels/808358975287722045/875438141610270740/1085499005305356308

### What would you like to be able to do?

currently after leaving the wallet for an undefined period of time requires the password to be entered to sign for tx's
this should be a feature that has some control from the user e.g. 30min, 1hr, 24hr, never?

**Comment by hyphenized** [comment] 2023-08-07 02:46
Completed, duplicate of #1151, #3471

**Closed** 2023-08-07 02:47 UTC
