### ISSUE TITLE
High Gas - tx fee for in-wallet swap

### ISSUE THREAD

**Issue by Naxsun** [tahowallet/extension#2330] opened 2022-09-29 11:17 UTC
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1024959663025967135

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Swap ETH for sUSD

### What did not work?

Gas was 19 gwei, swap fee $10.18

![image](https://user-images.githubusercontent.com/71384922/193017925-144661c4-5823-4923-abfd-5c95a03a13d6.png)

https://optimistic.etherscan.io/tx/0x0898520f21696b29701971084606cdb5f4a222fad2b37e5536e2ae9783de1aad

**Comment by Naxsun** [comment] 2022-10-20 06:59
Another user that reported this yesterday in version 0.17.2
- https://discord.com/channels/808358975287722045/888500174685614090/1032385131274584175
- https://optimistic.etherscan.io/tx/0x2b860b06aab8f27b809f446ea03aed9eeb3d714d656d65ae2a6e017d95f68672

**Comment by Naxsun** [comment] 2022-10-20 07:00
> Likely related to #2328

But since this is Optimism, a user can't set these settings. So would it happen in the extension itself?

**Comment by greg-nagy** [comment] 2022-11-14 12:46
Related context https://docs.google.com/document/d/18gscB4uF5XRnoCrZqjncQayAr0PP1gG2SR8LCtvkoqY/edit

**Comment by tallysam** [comment] 2023-02-15 15:30
We cannot reproduce this and will close as wont fix

**Comment by Naxsun** [comment] 2023-02-16 09:24
I think we should reopen, as I believe I'm able to reproduce. Below some screenshots:

To reproduce: 
- First make an in-wallet swap on Polygon, and change the gas
- Then directly after make an in-wallet swap on Opitmism

It seems to carry over Polygon gas settings to Optimism

- Below an example of that that I reproduced just now: 
- An in-wallet swap on Optimism should cost < $0.50. I have $41 of ETH in this wallet, yet the wallet says I don't have sufficient ETH to cover gas.
- It also says gas is 336 Gwei, which is not realistic.


<img width="441" alt="Screen Shot 2023-02-16 at 10 17 39" src="https://user-images.githubusercontent.com/71384922/219322806-6fccbec9-f411-4459-8c11-feb91f48c5a1.png">
<img width="486" alt="Screen Shot 2023-02-16 at 10 17 20" src="https://user-images.githubusercontent.com/71384922/219322832-ed4fc949-607e-4f22-8ce4-11236d14c214.png">
<img width="424" alt="Screen Shot 2023-02-16 at 10 17 33" src="https://user-images.githubusercontent.com/71384922/219322864-2f1db10a-445e-494e-925a-09f13722ebac.png">

**Closed** 2023-02-28 10:35 UTC
Labels: Type: Bug, Status: Pending, Priority: High
