### ISSUE TITLE
'Unexpected error' when attempting swap on SpookySwap

### ISSUE THREAD

**Issue by mr-michael** [tahowallet/extension#3327] opened 2023-04-27 01:56 UTC
An hour ago, I was able to connect my wallet, but then got an Unexpected Error...

<img width="986" alt="Screen Shot 2023-04-26 at 8 38 13 PM" src="https://user-images.githubusercontent.com/7005061/234740685-59acae4c-23ca-484c-8961-a0bcb7c27703.png">

Curiously (and happily) I was able to successfully swap just a moment ago

<img width="815" alt="Screen Shot 2023-04-26 at 9 57 32 PM" src="https://user-images.githubusercontent.com/7005061/234740576-7c524fcf-28f1-40db-9fac-e99135a44906.png">

<img width="611" alt="Screen Shot 2023-04-26 at 9 56 53 PM" src="https://user-images.githubusercontent.com/7005061/234740578-ba95e27e-9a49-427c-8fc5-b681c5740984.png">

**Comment by kkosiorowska** [comment] 2023-04-28 07:37
I have tried to reproduce but I wasn't able. 🤔 @mr-michael Do you have any logs for this issue?

**Comment by 0xDaedalus** [comment] 2023-05-02 13:26
I also am not able to reproduce

**Comment by Shadowfiend** [comment] 2023-07-12 03:10
Closing as not reproducible.

**Closed by Shadowfiend** 2023-07-12 03:10 UTC
Labels: Type: Bug
